---
# yaml-language-server: $schema=file://home/psacawa/.schema/kube/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-backend-config
  labels:
    app: backend
data:
  # BACKEND_HOST: test-backend-service
  BACKEND_HOST: test-backend-service
  BACKEND_PORT: "8080"
---
# yaml-language-server: $schema=file://home/psacawa/.schema/kube/pod.json
apiVersion: v1
kind: Pod
metadata:
  name: test-backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: test-backend-container
      image: 886185890074.dkr.ecr.us-east-2.amazonaws.com/test-backend-image:latest
---
# yaml-language-server: $schema=file://home/psacawa/.schema/kube/service.json
apiVersion: v1
kind: Service
metadata:
  name: test-backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
---
# yaml-language-server: $schema=file://home/psacawa/.schema/kube/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontend-pod
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: test-fronend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: test-frontend-container
          image: 886185890074.dkr.ecr.us-east-2.amazonaws.com/test-frontend-image:latest
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: test-backend-config
                  key: BACKEND_HOST
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: test-backend-config
                  key: BACKEND_PORT

---
# yaml-language-server: $schema=file://home/psacawa/.schema/kube/service.json
apiVersion: v1
kind: Service
metadata:
  name: test-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 8000
